export const genreMappings: { [key: string]: string[] } = {
  " Rock ": [
    "Album Rock",
    "Alternative Rock",
    "Art Rock",
    "Australian Alternative Rock",
    "Classic Rock",
    "Garage Rock",
    "Glam Rock",
    "Grunge",
    "Hard Rock",
    "Indie Rock",
    "Japanese Rock",
    "Kraut Rock",
    "Math Rock",
    "Modern Rock",
    "Progressive Rock",
    "Psychedelic Rock",
    "Punk Rock",
    "Rockabilly",
    "Southern Rock",
    "Surf Rock",
  ],
  " Metal ": [
    "Atmospheric Black Metal",
    "Avantgarde Metal",
    "Black Metal",
    "Death Metal",
    "Doom Metal",
    "Gothic Metal",
    "Groove Metal",
    "Heavy Metal",
    "Melodic Death Metal",
    "Metalcore",
    "Nu Metal",
    "Power Metal",
    "Progressive Metal",
    "Speed Metal",
    "Stoner Metal",
    "Symphonic Metal",
    "Thrash Metal",
    "Viking Metal",
  ],
  " Pop ": [
    "Adult Standards",
    "Arab Pop",
    "Baroque Pop",
    "Bubblegum Pop",
    "Chamber Pop",
    "Classic Pop",
    "Dance Pop",
    "Dream Pop",
    "Electro Pop",
    "Indie Pop",
    "J-Pop",
    "K-Pop",
    "Latin Pop",
    "Pop Rock",
    "Soft Pop",
    "Synth Pop",
    "Teen Pop",
    "Turkish Pop",
    "Vocal Pop",
  ],

  " Halk Müziği ": [
    "Appalachian Folk",
    "Celtic Folk",
    "Contemporary Folk",
    "Folk Rock",
    "Indie Folk",
    "Irish Folk",
    "Kurdish Folk",
    "Scandinavian Folk",
    "Singer-Songwriter",
    "Traditional Folk",
    "Turkish Folk",
    "World Folk",
  ],
  " Arabesk ": ["Arab Folk", "Arab Pop", "Arabic Jazz", "Egyptian Pop", "Lebanese Pop", "Rai", "Shaabi"],
  " Elektronik ": [
    "Ambient",
    "Chillwave",
    "Downtempo",
    "Drum and Bass",
    "Dubstep",
    "Electro",
    "Electro House",
    "Electronica",
    "IDM",
    "Minimal Techno",
    "Progressive House",
    "Techno",
    "Trance",
    "Trip Hop",
  ],
  " Alternatif ": [
    "Alternative Americana",
    "Alternative Country",
    "Alternative Hip Hop",
    "Alternative Metal",
    "Alternative Pop",
    "Alternative Rock",
    "Indie",
    "Indie Rock",
    "Lo-fi",
    "Post-Punk",
    "Shoegaze",
    "Surf Music",
    "Synth Pop",
    "Twee Pop",
  ],
  " Klasik Müzik ": [
    "Baroque",
    "Chamber",
    "Choral",
    "Classical",
    "Contemporary Classical",
    "Early Music",
    "Medieval",
    "Minimalism",
    "Modern Classical",
    "Opera",
    "Orchestral",
    "Renaissance",
    "Romantic",
    "Symphony",
  ],
  " Enstrümantal ": [
    "Acoustic Guitar",
    "Classical Guitar",
    "Film Score",
    "Instrumental Jazz",
    "Orchestral",
    "Piano",
    "String Quartet",
    "Synthesizer",
    "Theremin",
  ],
  " Hiphop / Rap ": [
    "Alternative Hip Hop",
    "Boom Bap",
    "British Hip Hop",
    "Cloud Rap",
    "East Coast Hip Hop",
    "Gangsta Rap",
    "Hip Hop",
    "Rap",
    "Trap",
    "Underground Hip Hop",
    "West Coast Hip Hop",
  ],
  " Jazz ": [
    "Acid Jazz",
    "Afro-Cuban Jazz",
    "Big Band",
    "Bossa Nova Jazz",
    "Free Jazz",
    "Gypsy Jazz",
    "Latin Jazz",
    "Modern Jazz",
    "Smooth Jazz",
    "Swing",
    "Traditional Jazz",
    "Vocal Jazz",
  ],
  " Punk ": ["Hardcore Punk", "Pop Punk", "Punk", "Punk Blues", "Punk Rock", "Riot Grrrl", "Ska Punk", "Street Punk"],
  " Blues ": [
    "Acoustic Blues",
    "Blues",
    "Blues Rock",
    "Chicago Blues",
    "Contemporary Blues",
    "Delta Blues",
    "Electric Blues",
    "Modern Blues",
    "Soul Blues",
    "Swamp Blues",
  ],
} as const;
